apiVersion: v1
kind: Service
metadata:
  name: google
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: ExternalName
  externalName: www.google.cl
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: google
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "www.google.cl"
spec:
  rules:
  - host: my.service.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: google
          servicePort: 443
